### ISSUE TITLE
Error on vaultClient.register

### ISSUE THREAD

**Issue by lukeburns** [stevenzeiler/ripple-vault-client#6]
I'm getting the following error when running vaultClient.register:

```
/Users/luke/Code/ripple/node_modules/ripple-vault-client/node_modules/ripple-lib/build/sjcl.js:1744
      throw new sjcl.exception.notReady("generator isn't seeded");
            ^
NOT READY: generator isn't seeded
```

**Comment by shekenahglory** [comment]
This version isnt supported anymore, its been merged into ripple-lib: https://github.com/ripple/ripple-lib/blob/develop/docs/VAULTCLIENT.md

if you still have the error there, open an issue

**Comment by lukeburns** [comment]
oh wow, didn't catch that. thanks
